export const artists = [
  { name: 'BLOK3', id: '1GMwSpFzrLd12jUX15bHB6' },
  { name: 'Ati242', id: '6bGOmNBU1AOgttgOjh0ldf' },
  { name: 'Semicenk', id: '1CcZoULzFHa8Uhwo6OlQcp' },
  { name: 'Era7capone', id: '4UW9Hdsrx9kX2HdJ90jRKM' },
  { name: 'Lvbel C5', id: '0V2oXYR7DtrZAEFeILRW2r' },
  { name: 'UZI', id: '51DevdOxIJin6DB1FXJpD1' },
  { name: 'Sezen Aksu', id: '64d1rUxfizSAOE9UbMnUZd' },
  { name: 'Poizi', id: '250LLR8V4fFq1XFzAB1ZN5' },
  { name: 'Motive', id: '6sBSLIunx1Je0Y2T77wpkP' },
  { name: 'AKDO', id: '17EAWIoXAMU9Vo9xRrdZQ0' },
  { name: 'Gülşen', id: '1F2v33FQTavJyaD7ZsyhdA' },
  { name: 'Yalın', id: '46zuW8tHxwahYn7VNMgYTa' },
  { name: 'Dedublüman', id: '5PRW6j58xEEWL4DDVEITKT' },
  { name: 'Hande Yener', id: '08mjMUUjyTchMHCW7evc3R' },
  { name: 'SNOW', id: '58H98oCs7wfe6XZOgIaT0q' },
  { name: 'Ebru Gündeş', id: '5AboYJAlMb9FGadTTDKRoN' },
  { name: 'Ezhel', id: '6LnJKrtFnTEGdbWQ2riWCL' },
  { name: 'manifest', id: '2WjzL05RyqIk5n53sZc9nf' },
  { name: 'Simge', id: '4StjyzjcmZ7a9QncHVf0pu' },
  { name: 'Sertab Erener', id: '4W31XN2JH8mC54NkHdh04s' },
  { name: 'Tarkan', id: '2yMN0IP20GOaN6q0p0zL5k' },
  { name: 'Hadise', id: '0wCKNMsqYasJBFVagjay49' },
  { name: 'Mabel Matiz', id: '1dpqJqIuNqideTvmxBsSku' },
  { name: 'Edis', id: '1AM52XHXnWAEqnQwpxTLWm' },
  { name: 'Zeynep Bastık', id: '1mpOD8ZwHnbsryIuXWq0R1' },
  { name: 'İrem Derici', id: '5h2jTdwf4p0dM34aBykPzZ' },
  { name: 'Melike Şahin', id: '16GyR4WfCnIT2XST4ZLl2B' },
  { name: 'Emir Can İğrek', id: '4XP7cGw4t8BqZ8Du5q3bHg' },
  { name: 'Aleyna Tilki', id: '4ckLjJztj53Ifid7WHweBn' },
  { name: 'Sefo', id: '1ITjgqpqMDJlqZGAK3mlPQ' },
  { name: 'Güneş', id: '0L3wrFI3QcbXAvFL7IaPQX' },
  { name: 'Batuflex', id: '15AZJFNrXtIN4Nk8BIOnS2' },
  { name: 'Reckol', id: '5FqTuN42w2zGw4Pzd50yaS' },
  { name: 'Murda', id: '2y1VzMKAa5nmfXKtJL9jnj' },
  { name: 'Mela Bedel', id: '55WpZ8ig2SFNvQpDHPUrgY' },
  { name: 'Ajda Pekkan', id: '27XMnTLvCO7t3qGlQyTMkF' },
  { name: 'Mustafa Sandal', id: '0mkH5jj3goQ51JtPKVodTo' },
  { name: 'Madrigal', id: '2aZlYOswKNlrwqpuTsckKd' },
  { name: 'Duman', id: '6RTC1abMgBC7Krg6qJQHJh' },
  { name: 'Kenan Doğulu', id: '2RQ8NtUmg5y6tfbvCwX8jI' },

  { name: 'Sıla', id: '5gFPi3KWXEwA9bLEO47Ow0' },
  { name: 'Murat Boz', id: '53oeVgECSa18dkHBQ9X6Eh' },
  { name: 'Demet Akalın', id: '1U449OOb70EZlElNjLMwCM' },
  { name: 'Buray', id: '1qZ684TB9E1BjH58btdtYd' },
  { name: 'Reynmen', id: '1Fg19vpUJpAAPFjnKaVYVW' },
  { name: 'Ceza', id: '28Qbi9jTj2eej21P2mImZI' },
  { name: 'Sagopa Kajmer', id: '1KXTegXtnCPKXjRaX1llcD' },
  { name: 'Norm Ender', id: '3S6gaE89XewFAvZqsMuJDJ' },
  { name: 'Şanışer', id: '5LUxu287CsPM7jy3yS3l86' },
  { name: 'Gazapizm', id: '2boacFGRX1WIo7NFS8B0F2' },
  { name: 'Contra', id: '3tJELJoPZ4VTKmL0vppqLj' },
  { name: 'Khontkar', id: '1iJrQKRh5aJnp6cG5lpITr' },
  { name: 'Grogi', id: '40PllTYqoDKRna2jm9Gf8D' },
  { name: 'Şebnem Ferah', id: '74xBVPWYoSf5pvo5IkePRO' },
  { name: 'mor ve ötesi', id: '5ixQSDvAMa5O758xG8MWXT' },
  { name: 'maNga', id: '7rEIUw67hRTgievwuKQGSj' },
  { name: 'Model', id: '23xJQJM7peht77DF6YNEoq' },
  { name: 'Melek Mosso', id: '5IAxUWLiTMsvc1oWPrczNj' },
  { name: 'Derya Uluğ', id: '7A6T0nTpXnPXDUGM1yEjEj' },
  { name: 'Fettah Can', id: '17fJCykpa2EqIioh0zamN9' },
  { name: 'Cem Adrian', id: '2AWUCT9xtcvkjpFq1ZgpPj' },
];
